site_name: mkdocs
site_url: https://szxzip.github.io/mkdocs
repo_url: https://github.com/szxzip/mkdocs
repo_name: szxzip/mkdocs
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-4
  logo:
  favicon:
  language: en
  font:
    text: Noto Sans
    code: Noto Sans Mono
plugins:
  - search
copyright: © 2025 szxzip, CC BY-SA 4.0
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/szxzip
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/szxzip
